/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1.Frontend;
import com.mycompany.mavenproject1.Backend.AdminRole;
import com.mycompany.mavenproject1.Backend.EmployeeUser;
import java.util.ArrayList;
/**
 *
 * @author nadamourad
 */
public class AdminRoleWindow extends javax.swing.JFrame {
private TableView tableView;
private EmployeeUser[]employeeData;
private AdminRole admin;
    /**
     * Creates new form AdminRole
     */
    public AdminRoleWindow() {
        initComponents();
        setTitle("Admin Role");
        tableView=null;
        this.admin=new AdminRole();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddEmployee_btn = new javax.swing.JButton();
        RemoveEmployee_btn = new javax.swing.JButton();
        ViewEmployees_btn = new javax.swing.JButton();
        Logout_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AddEmployee_btn.setBackground(new java.awt.Color(0, 0, 0));
        AddEmployee_btn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        AddEmployee_btn.setForeground(new java.awt.Color(255, 255, 255));
        AddEmployee_btn.setText("Add Employee");
        AddEmployee_btn.setOpaque(true);
        AddEmployee_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEmployee_btnActionPerformed(evt);
            }
        });

        RemoveEmployee_btn.setBackground(new java.awt.Color(0, 0, 0));
        RemoveEmployee_btn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        RemoveEmployee_btn.setForeground(new java.awt.Color(255, 255, 255));
        RemoveEmployee_btn.setText("Remove Employee");
        RemoveEmployee_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveEmployee_btnActionPerformed(evt);
            }
        });

        ViewEmployees_btn.setBackground(new java.awt.Color(0, 0, 0));
        ViewEmployees_btn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        ViewEmployees_btn.setForeground(new java.awt.Color(255, 255, 255));
        ViewEmployees_btn.setText("View Employees");
        ViewEmployees_btn.setOpaque(true);
        ViewEmployees_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewEmployees_btnActionPerformed(evt);
            }
        });

        Logout_btn.setBackground(new java.awt.Color(0, 0, 0));
        Logout_btn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        Logout_btn.setForeground(new java.awt.Color(255, 255, 255));
        Logout_btn.setText("Logout");
        Logout_btn.setOpaque(true);
        Logout_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(AddEmployee_btn)
                    .addComponent(RemoveEmployee_btn)
                    .addComponent(ViewEmployees_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Logout_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {AddEmployee_btn, Logout_btn, RemoveEmployee_btn, ViewEmployees_btn});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(AddEmployee_btn)
                .addGap(18, 18, 18)
                .addComponent(RemoveEmployee_btn)
                .addGap(18, 18, 18)
                .addComponent(ViewEmployees_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Logout_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {AddEmployee_btn, Logout_btn, RemoveEmployee_btn, ViewEmployees_btn});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddEmployee_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEmployee_btnActionPerformed
        this.setVisible(false);
        AddEmployee addEmployee=new AddEmployee();
        addEmployee.setVisible(true);
       
        
        
    }//GEN-LAST:event_AddEmployee_btnActionPerformed

    private void RemoveEmployee_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveEmployee_btnActionPerformed
this.setVisible(false);
RemoveEmployee removeEmployee= new RemoveEmployee(this.admin);
removeEmployee.setVisible(true);


    }//GEN-LAST:event_RemoveEmployee_btnActionPerformed

    private void ViewEmployees_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewEmployees_btnActionPerformed

   
      employeeData=admin.getListOfEmployees();
      if(tableView==null){
          tableView=new TableView(new String[]{"Name","EmployeeId","Email","Address","Phone"});
          tableView.setTitle("Employees");
      }
      String [][]tableData=new String[employeeData.length][5];
      for(int i=0;i<employeeData.length;i++){
       tableData[i]=employeeData[i].lineRepresentation().split(",");
       
      }
      tableView.SetData(tableData);
      tableView.setVisible(true);
     
        
    }//GEN-LAST:event_ViewEmployees_btnActionPerformed

    private void Logout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout_btnActionPerformed
 AdminRole admin=new AdminRole();
 admin.logout();
    }//GEN-LAST:event_Logout_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminRoleWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminRoleWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminRoleWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminRoleWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminRoleWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddEmployee_btn;
    private javax.swing.JButton Logout_btn;
    private javax.swing.JButton RemoveEmployee_btn;
    private javax.swing.JButton ViewEmployees_btn;
    // End of variables declaration//GEN-END:variables
}
